app:
  name: bulk_emailer
  dry_run: true

email:
  smtp_server: smtp.gmail.com
  smtp_port: 587
  sender_email: zobelahadu@gmail.com

auth:
  sender_password: os.getenv("EMAIL_PASSWORD")

campaign:
  subject: "Weekly Update"
  body_file: "email_body.txt"
  recipients_file: "recipients.csv"
  max_emails_per_run: 50

logging:
  log_file: "/home/leul/automation/email.log"

