app:
  name: bulk_emailer
  dry_run: True
  cron:
  minute: 36
  hour: 18
  day_of_month: "*"
  month: "*"
  day_of_week: "*"

email:
  smtp_server: smtp.gmail.com
  smtp_port: 465
  sender_email: zobelahadu@gmail.com



campaign:
  subject: "Weekly Update"
  body_file: "email_body.txt"
  recipients_file: "recipients.txt"
  max_emails_per_run: 50

logging:
  log_file: "/home/leul/automation/email.log"

